services:

  nginx:
    image: nginx:latest
    configs:
      - source: vote-nginx-conf
        target: /etc/nginx/conf.d/default.conf
        
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 250M

  worker:
    build: 
      context: https://github.com/UffizziCloud/example-voting-app-serverlessdemo
      dockerfile: ./worker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build: 
      context: https://github.com/UffizziCloud/example-voting-app-serverlessdemo
      dockerfile: ./vote/Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    build: 
      context: https://github.com/UffizziCloud/example-voting-app-serverlessdemo
      dockerfile: ./result/Dockerfile
    
configs:
  vote-nginx-conf:
    file: vote.conf
    
continuous_preview:
  deploy_preview_when_image_tag_is_created: true
  share_to_github: true

ingress:
  service: nginx
  port: 8080
